select * from processed_data;

# Q1 what is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) as revenue
from processed_data
group by gender;

# Q2 which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from processed_data
where discount_applied = "Yes" and purchase_amount>= (select avg(purchase_amount) from processed_data);

# Q3 which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating),2)
from processed_data
group by item_purchased
order by avg(review_rating) desc
limit 5;

# Q4 compare the average purchase amount between standard and express shipping.
select shipping_type, avg(purchase_amount)
from processed_data
where shipping_type in ('Express','Standard')
group by shipping_type;


# Q5 Do subscribed customers spend more? compare average spend and total revenue between subscribers 
# -- and non-subscribers.
select subscription_status, avg(purchase_amount)
from processed_data
group by (subscription_status)
order by avg(purchase_amount) desc;

# Q6 which 5 products have the highest percentage of purchase with discounts applied?
select item_purchased, avg(purchase_amount)
from processed_data
where discount_applied = "Yes"
group by item_purchased
order by avg(purchase_amount) desc
limit 5;

# Q7 Which color was purchased the most?
select color, count(*) as total_purchased
from processed_data
group by color;

# Q8 what are the top 3 most purchased products within each category?
select category, count(category)
from processed_data
group by category
order by count(category) desc
limit 3;

# Q9 Which season has the highest number of purchases?
select season, count(*) as total_purchases
from processed_data
group by season
order by total_purchases desc;

# Q10 what is the revenue contribution of each age group?
select age, sum(purchase_amount) as revenue
from processed_data
group by age
order by revenue desc;